version: 2
jobs:
  build:
    docker:
      - image: tomcat:jdk11-adoptopenjdk-openj9
        auth:
          username: $DOCKERHUB_ID
          password: $DOCKERHUB_PW
    steps:
      - run:
          name: Echo Test
          command: 'echo test'
      - run:
          name: Print Date
          command: 'date'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
