version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u232-jdk
    steps:
      - run:
          name: Echo Test
          command: 'echo test'
      - run:
          name: Print Date
          command: 'date'
      - run:
          name: Check OS Information
          command: 'cat /etc/os-release'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
