version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u232-jdk
    steps:
      - checkout
      - run : 'echo date'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
