version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    steps:
      - run:
          name: Echo Test
          command: 'echo test'
      - run:
          name: Print Date
          command: 'date'
      - run:
          name: OS Checking
          command: 'cat /etc/os-release'
workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
